/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package emobile;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class StockkeItemUI extends javax.swing.JFrame {
    Connection conn=null; 
     ResultSet rs =null; 
     PreparedStatement pst=null; 
    /**
     * Creates new form ItemUI
     */
    public StockkeItemUI() {
        initComponents();
         distable();
    }
        private void distable() { 
    
        try { 
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url="jdbc:sqlserver://localhost:1433;databaseName=77OOP062;user=sa;password=hnd";
        Connection conn= DriverManager.getConnection(url);
        
        String sql ="select * from items"; 
        pst=conn.prepareStatement(sql); 
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs)); 
        } 
        
        catch (Exception e) { 
        JOptionPane.showMessageDialog(null, e); 
       } 
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldItemCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldItemDescription = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldReorderLevel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUnitPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRemarks = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldItemName = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Item code");

        jTextFieldItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemCodeActionPerformed(evt);
            }
        });

        jLabel3.setText("Item Description");

        jTextFieldItemDescription.setToolTipText("");

        jLabel4.setText("Reorder Level");

        jLabel5.setText("Unit Price");

        jLabel6.setText("Remarks");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("STOCK DETAILS");

        jTextFieldItemName.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jTextFieldItemName.setText("    Select From the Menu List");
        jTextFieldItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemNameActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "eMobile X1", "eMobile X2", "eMobile X3", "eMobile E1", "eMobile E2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Brand", "Reorder Level", "Unit Price", "Remark"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldItemDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(jTextFieldReorderLevel)
                                    .addComponent(jTextFieldUnitPrice)
                                    .addComponent(jTextFieldRemarks)
                                    .addComponent(jTextFieldItemCode, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldItemName)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemCodeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        String s = ((String) jComboBox1.getSelectedItem());
        JOptionPane.showMessageDialog(this, "You have Selected "+s);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jTextFieldItemCode.getText() .isEmpty())
        {
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Item Code", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextFieldItemDescription.getText() .isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Item Description", "Dialog", JOptionPane.ERROR_MESSAGE);
        }

        else if(jTextFieldUnitPrice.getText() .isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Unit Price", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        
        
        else{
        
            items obj=new items();
            jTextFieldItemName.setText((String) jComboBox1.getSelectedItem());
            
            obj.setItem_code(jTextFieldItemCode.getText());
            obj.setName(jTextFieldItemName.getText());
            obj.setDescription(jTextFieldItemDescription.getText());
            obj.setReorder_Level(Integer.parseInt(jTextFieldReorderLevel.getText()));
            obj.setUnit_Price(Double.parseDouble(jTextFieldUnitPrice.getText()));
            obj.setRemarks(jTextFieldRemarks.getText());
            JOptionPane.showMessageDialog(new JFrame(), "Successfully Inserted", "Dialog", JOptionPane.INFORMATION_MESSAGE);
            try{
            obj.additems(obj);
            } catch (Exception ex) {
           System.out.println(" "+ex.toString());
            }
            distable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url="jdbc:sqlserver://localhost:1433;databaseName=77OOP062;user=sa;password=hnd";
        Connection conn= DriverManager.getConnection(url);
        String value1= jTextFieldItemCode.getText();
        String value2=jTextFieldItemName.getText();
        String value3=jTextFieldItemDescription.getText();
        String value4=jTextFieldReorderLevel.getText();
        String value5=jTextFieldUnitPrice.getText();
        String value6=jTextFieldRemarks.getText();

        String sql= "UPDATE items SET Item_code='"+value1+"',Name='"+value2+"',Description='"+value3+"',"
                + "Reordered_Level='"+value4+"',Unit_Price='"+value5+"',Remark='"+value6+"' WHERE Item_code='"+value1+"'";
        pst=conn.prepareStatement(sql);
        pst.execute();
        
            if(jTextFieldItemCode.getText() .isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Item Code", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextFieldItemName.getText() .isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Item Name", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextFieldItemDescription.getText() .isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Item Description", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextFieldReorderLevel.getText() .isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Reorder Level", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextFieldUnitPrice.getText() .isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Unit Price", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextFieldRemarks.getText() .isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Enter the Remarks", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
        JOptionPane.showMessageDialog(null, "Updated Successfully");
        }
        }catch(Exception e){;
        JOptionPane.showMessageDialog(null, e);
        }
        distable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         jTextFieldItemCode.setText("");
         jTextFieldItemName.setText("");
         jTextFieldItemDescription.setText("");
         jTextFieldReorderLevel.setText("");
         jTextFieldUnitPrice.setText("");
         jTextFieldRemarks.setText("");
         JOptionPane.showMessageDialog(new JFrame(), "Add New Details", "Dialog", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         int selectedRowIndex = jTable1.getSelectedRow();
        
        jTextFieldItemCode.setText(model.getValueAt(selectedRowIndex, 0 ).toString());
        jTextFieldItemName.setText(model.getValueAt(selectedRowIndex, 1 ).toString());
        jTextFieldItemDescription.setText(model.getValueAt(selectedRowIndex, 2 ).toString());
        jTextFieldReorderLevel.setText(model.getValueAt(selectedRowIndex, 3 ).toString());
        jTextFieldUnitPrice.setText(model.getValueAt(selectedRowIndex, 4 ).toString());
        jTextFieldRemarks.setText(model.getValueAt(selectedRowIndex, 5 ).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked



    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockkeItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockkeItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockkeItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockkeItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockkeItemUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldItemCode;
    private javax.swing.JTextField jTextFieldItemDescription;
    private javax.swing.JTextField jTextFieldItemName;
    private javax.swing.JTextField jTextFieldRemarks;
    private javax.swing.JTextField jTextFieldReorderLevel;
    private javax.swing.JTextField jTextFieldUnitPrice;
    // End of variables declaration//GEN-END:variables

    private void hide(String stockKeeperUI) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
